server:
  port: 8053
spring:
  datasource:
    name: kc_tiku
    druid:
      url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      filters: stat
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      pool-prepared-statements: false
  redis:
    host: localhost
    port: 6379
    password:
    database: 3
  application:
    name: np-up
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://114.55.168.93:8900/eureka/
    enabled: false
swagger:
  title: template
  description: template -- ${spring.application.name}
  version: 1.0.0
  base-package: com.nap.up
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    cache-enabled: true

system:
  session:
    type: session